In [1]:
import numpy as np
import pandas as pd

In [5]:
# 1

M1 = np.array([[23, 50], [7, 12]])
M2 = np.array([[57, 67], [99, 43]])
M3 = np.array([[75, 21], [57, 12]])
M4 = np.array([[87, 26], [18, 84]])

tensor = np.array([M1, M2, M3, M4])
tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [11]:
# 2

A = np.array([[23, 50, 19], [7, 12, 109], [57, 67, 98]])
B = np.array([[17, 22, 19]])

print(A)
print(B)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
[[17 22 19]]


In [12]:
A * B

array([[ 391, 1100,  361],
       [ 119,  264, 2071],
       [ 969, 1474, 1862]])

In [15]:
# 3

M = np.array([[23, 50, 19], [7, 12, 109], [57, 67, 98]])
M

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [18]:
# Transpose

M_t = M.T
M_t

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [17]:
# determinan

np.linalg.det(M)

131344.0000000002

In [19]:
np.linalg.det(M_t)

131343.99999999997

In [20]:
# inverse

np.linalg.inv(M)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])

In [21]:
np.linalg.inv(M_t)

array([[-0.0466485 ,  0.04208034, -0.00163692],
       [-0.02761451,  0.00891552,  0.0099662 ],
       [ 0.03975819, -0.01807467, -0.00056341]])